Before we proceed and download the data available from the paper, we must first delve into some of the details in Supplementary Data.
Your first task is to look through the Supplementary Data and find the annotation relating the tumor types to the isotopic labels used.

::: {.question}
How did you find the required information? Describe the steps you took. How much time did it take?
:::

::: {.callout-note collapse="true"}
#### Hint
If you have not been able to find the annotations, open Supplementary Data 1, and then go to the tab called "Tumor annotations".
:::

To better understand the supplementary data, we have prepared guiding questions to aid in interpreting the table. You can find the supplementary data in the paper [here](https://www.nature.com/articles/s41467-019-09018-y#Sec15).

::: {.question}
Provide a brief description of the content presented in the table.
:::

::: {.question}
What information does the tumor ID represent?
:::

::: {.question}
Briefly describe TMT-labeled mass spectrometry proteomics data and explain the experimental procedure involved.
:::
