project:
  type: website

website:
  title: "Clinical Proteomics"

# Add the author and description to the metadata section
#metadata:
#  author: "Jacob Fredegaard Hansen"
#  description: "Outline for clinical proteomics"

# Navbar configuration
navbar:
#  title: "Clinical Proteomics"
  left:
    - text: Introduction
      href: index.qmd
    - text: Getting Started
      href: gettingstarted.qmd
    - text: Setup
      href: setup.qmd
    - text: ColabFold
      href: colabfold.qmd
    - text: Course Materials
      href: coursematerials.qmd
    - text: Teaching Module
      href: teachingmodule.qmd
    - text: Contributors
      href: contributors.qmd

format:
  html:
    theme:
          light: [materia, css/materialight.scss]
          dark: darkly
#    include-after-body:
#      - javascripts/mathjax.js
#      - https://polyfill.io/v3/polyfill.min.js?features=es6
#      - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
#    favicon: images/favicon.png
#    logo: images/logo.png
    toc: true
#    toc-depth: 3
#    navigation:
#      depth: 3
#    highlight-style: github

# Bibliography for citations
#bibliography: references.bib

# Add extra configuration
#extra:
#  google-analytics: !expr Sys.getenv("GOOGLE_ANALYTICS_KEY")
#  social-links:
#    - icon: github
#      href: https://github.com/hds-sandbox
#    - icon: twitter
#      href: https://twitter.com/ucph_heads

# Markdown extensions
#markdown:
#  extensions: 
#    - abbr
#    - admonition
#    - footnotes
#    - attr
#    - def_list
#    - tables
#    - fenced_code_blocks
#    - table_of_contents
#    - callouts
#    - yaml_metadata_block

# Input/output directories
#output-dir: docs
#input-dir: develop
