---
title: "Proteomics Hub"
subtitle: Proteomics resources in HDS Sandbox
format:
  html:
    toc: false
    page-layout: full
date-modified: last-modified
date-format: long
date: 2024-09-11
---


Discover the world of proteomics with the Proteomics Hub of the Sandbox, offering educational resources based on the **Proteomics Sandbox** and **Colabfold** apps on UCloud
- an accessible resource for biomedical students and non-computational researchers.
**Proteomics Sandbox** provides a stable platform for proteomics software tools with an accessible Graphical User Interface (GUI) without requiring any coding skills.
You can also learn to predict protein structures based on sequence data with the **ColabFold** workshop.
This hands-on experience offers insights into the exciting field of proteomics analysis and is accessible for all UCloud users.

<!-- :::{.callout-warning title="Disclaimer and requirements"}

Currently, the educational material on proteomics is only available at UCloud, making it only accessible for UCloud-users.

    - Access to UCloud and sufficient resources to run the application
    - Basic computational knowledge, including familiarity with the UCloud environment
    - Familiarity with proteomics analysis techniques
::: -->


## Learning Proteomics with the Proteomics Hub

The Proteomics Hub offers the following resources for learning and practicing (clinical) proteomics data analysis:

- The [Proteomics Sandbox app](ucloud.qmd), which is a virtual machine with software readily available for clinical proteomics data analysis.
- The [Clinical Proteomics teaching module](TeachingModule/teachingmodule.qmd), an interactive online course on data processing based on the **Proteomics Sandbox** app.
- Separate interactive mini-course on [Annotating proteomics data with SDRF](sdrf.standalone.qmd), which is also included in the **Clinical Proteomics teaching module**.
- A [walkthrough guide on annotating a COVID-19 dataset](sdrf.guide.covid.qmd) using [lesSDRF](https://lessdrf.streamlit.app/).
- The [ColabFold workshop](colabfold.qmd), which is an independent teaching material for learning to predict protein structures from sequence data based on AlphaFold.

If you are keen on delving deeper into proteomics, either through experimental or computational approaches, take a look at the following courses available at SDU:

- [BMB535: Experimental Proteomics - Characterization of cellular signaling using quantitative proteomics](https://odin.sdu.dk/sitecore/index.php?a=searchfagbesk&internkode=bmb535&lang=en)
- [BMB542: Biomedical mass spectrometry – principles and applications](https://odin.sdu.dk/sitecore/index.php?a=searchfagbesk&internkode=bmb542&lang=en)
- [BMB834: Protein structure, dynamics and modelling](https://odin.sdu.dk/sitecore/index.php?a=fagbesk&id=115655&lang=en&listid=)
- [BMB831: Biostatistics in R II](https://odin.sdu.dk/sitecore/index.php?a=fagbesk&id=123609&lang=en&listid=)
- [BMB210: Advanced methods in protein mass spectrometry and proteomics](https://odin.sdu.dk/sitecore/index.php?a=fagbesk&id=121176&lang=en&listid=)

Other recommended online sources on proteomics include:

- Comprehensive materials for **Quantitative Proteomics** available on [GitHub](https://github.com/veitveit/training-quantitative-proteomics).
