---
title: "Clinical Proteomics"
subtitle: Clinical proteomics on Ucloud with the sandbox
format:
  html:
    toc: false
    page-layout: full
css: css/styles.css
date-modified: last-modified
date-format: long
date: 2024-09-11
#bibliography: resources/references.bib
---


Discover the world of proteomics with the Clinical Proteomics module of the Sandbox, offering the Proteomics Sandbox app on UCloud - an accessible resource for biomedical students and non-computational researchers. With a user-friendly interface and a lightweight clone feature, the app is perfect for those without extensive coding knowledge, providing a stable platform for proteomics software tools. You can also learn to predict protein structures based on sequence data with the independent ColabFold workshop, available on UCloud. This hands-on experience offers insights into the exciting field of proteomics analysis and is accessible for all UCloud-users.  

New course materials are being developed constantly to enhance your education and training in clinical proteomics data analysis. Stay tuned!

:::{.callout-warning title="Disclaimer and requirements"}

Currently, the educational material on proteomics is only available at UCloud, making it only accessible for UCloud-users.

    - Access to UCloud and sufficient resources to run the application
    - Basic computational knowledge, including familiarity with the UCloud environment
    - Familiarity with proteomics analysis techniques
:::


## Learning Clinical Proteomics with the Sandbox
The Clinical Proteomics Module offers a comprehensive resource for learning and practicing clinical proteomics data analysis. The module consists of the following components:

- The Proteomics Sandbox app, which is a virtual machine with software readily available for clinical proteomics data analysis.  
- ColabFold workshop, which is an independent teaching material for learning to predict protein structures from sequence data based on AlphaFold.  

In the future, additional course materials will be made available to provide comprehensive teaching and education in clinical proteomics. With the Clinical Proteomics Module, students and researchers have the opportunity to work with real-world clinical data, gain practical experience in analyzing and interpreting such data, and enhance their knowledge and skills in clinical proteomics data analysis.

Explore the various sections of the proteomics module by clicking on the tabs above.
